post_install() {
  echo "=== Creating system users ==="
  systemd-sysusers

  echo "=== Reloading systemd manager configuration ==="
  systemctl daemon-reload

  echo "start with systemctl enable --now vllm-qwen3.service"
}

post_upgrade() {
  post_install "$@"
}

post_remove() {
  echo "=== Stopping services ==="
  systemctl disable --now vllm-qwen3.service || true

  echo "=== Removing podman images ==="
  podman rmi docker.io/vllm/vllm-openai:latest || true

  echo "=== Removing managed data in /var/lib/vllm-qwen3 ==="
  rm -rf /var/lib/vllm-qwen3

  echo "=== Removing system users ==="
  userdel vllm || true

  echo "=== Reloading systemd manager configuration ==="
  systemctl daemon-reload
}
