post_install() {
  echo "=== Reloading systemd manager configuration ==="
  systemctl daemon-reload
}

post_upgrade() {
  post_install "$@"
}

post_remove() {
  echo "=== Removing podman container localhost/vllm-qwen36 ==="
  podman rmi localhost/vllm-qwen36:latest || true
  podman builder prune

  echo "=== Deleting local models in /var/lib/local-agents ==="
  rm -rf /var/lib/local-agents

  echo "=== Reloading systemd manager configuration ==="
  systemctl daemon-reload
}
