post_install() {
  echo "=== Reloading systemd manager configuration ==="
  systemctl enable vllm-qwen36.service hermes-agent.service
  systemctl daemon-reload
}

post_upgrade() {
  post_install "$@"
}

post_remove() {
  echo "=== Removing podman images ==="
  podman rmi docker.io/vllm/vllm-openai:latest || true
  podman rmi docker.io/nousresearch/hermes-agent:latest || true

  echo "=== Deleting local data in /var/lib/${pkgname} ==="
  rm -rf /var/lib/local-agents

  echo "=== Reloading systemd manager configuration ==="
  systemctl daemon-reload
}
